# -*- coding: utf-8 -*-
"""CRUX_challengeSafra Fase3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ue7aKfO-HXfwFV8oyTM4zb2LVYV-MYyZ
"""

import numpy as np
import pandas as pd
import sympy as sp
import matplotlib.pyplot as plt

! sudo pip install unidecode

import matplotlib.pyplot as plt
from wordcloud import WordCloud
import re
from unicodedata import normalize
import unidecode
import string
from spacy.lang.pt.stop_words import STOP_WORDS

dados_safra = pd.read_csv('DadosSafraAG0-Ficticios.csv',
                           sep = ';',
                           decimal = ',',
                           encoding = 'latin1')

dados_safra.head()

dados_safra['tempoAcesso'].describe()

dados_safra.groupby('paginaSaida') \
                 .agg(n_user = pd.NamedAgg('paginaSaida', 'count')) \
                 .reset_index()

dados_safra.groupby('usuarioOnline') \
                 .agg(n_user = pd.NamedAgg('usuarioOnline', 'count')) \
                 .reset_index()

labels= ['offline', 'online']
vals = [746, 254]

fig, ax = plt.subplots(figsize=(12, 5))

ax.pie(vals, labels=labels, autopct='%.0f%%')
ax.set_title('Status dos Usuários', fontsize=16)
plt.show()

dados_safra.groupby('statusSaida') \
                 .agg(n_user = pd.NamedAgg('statusSaida', 'count')) \
                 .reset_index()

dados_safra.groupby('avaliacao.r') \
                 .agg(n_user = pd.NamedAgg('avaliacao.r', 'count')) \
                 .reset_index()

labels= ['n/ avaliado', 'negativa', 'positiva']
vals = [239, 510, 251]

fig, ax = plt.subplots(figsize=(12, 5))

ax.pie(vals, labels=labels, autopct='%.0f%%')
ax.set_title('Avaliações', fontsize=16)
plt.show()

def quartil1(x):
  return np.quantile(x, 0.25)

def quartil3(x):
  return np.quantile(x, 0.75)



dados_safra.groupby('usuarioOnline') \
           .agg(tempo_min = pd.NamedAgg('tempoAcesso', 'min'),
                tempo_max = pd.NamedAgg('tempoAcesso', 'max'),
                tempo_mean = pd.NamedAgg('tempoAcesso', 'mean'),
                tempo_mediano = pd.NamedAgg('tempoAcesso', 'median'),
                tempo_q1 = pd.NamedAgg('tempoAcesso', quartil1),
                tempo_q3 = pd.NamedAgg('tempoAcesso', quartil3),
                tempo_dp = pd.NamedAgg('tempoAcesso', 'std')) \
          .reset_index()

dados_safra.groupby('avaliacao.r') \
           .agg(tempo_min = pd.NamedAgg('tempoAcesso', 'min'),
                tempo_max = pd.NamedAgg('tempoAcesso', 'max'),
                tempo_mean = pd.NamedAgg('tempoAcesso', 'mean'),
                tempo_mediano = pd.NamedAgg('tempoAcesso', 'median'),
                tempo_q1 = pd.NamedAgg('tempoAcesso', quartil1),
                tempo_q3 = pd.NamedAgg('tempoAcesso', quartil3),
                tempo_dp = pd.NamedAgg('tempoAcesso', 'std')) \
          .reset_index()

dados_safra.groupby('codigo') \
           .agg(tempo_min = pd.NamedAgg('tempoAcesso', 'min'),
                tempo_max = pd.NamedAgg('tempoAcesso', 'max'),
                tempo_mean = pd.NamedAgg('tempoAcesso', 'mean'),
                tempo_mediano = pd.NamedAgg('tempoAcesso', 'median'),
                tempo_q1 = pd.NamedAgg('tempoAcesso', quartil1),
                tempo_q3 = pd.NamedAgg('tempoAcesso', quartil3),
                tempo_dp = pd.NamedAgg('tempoAcesso', 'std')) \
          .reset_index()

























